config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  resources :rooms do
    resources :messages
  end

  root "pages#home"
  devise_for :users
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  devise_scope :user do 
    get 'users', to: 'devise/session#new'
  end

  get 'user/:id', to: 'users#show', as: 'user'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit {broadcast_append_to room}
  before_create :confirm_participant

  def confirm_participant
    return unless room.is_private
    is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
    throw :abort unless is_participant
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> {where(is_private: false)}

  after_create_commit {broadcast_if_public}
  has_many :messages
  has_many :participants, dependent: :destroy

  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end

  def self.create_private_room(users, room_name) 
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, uniqueness: true, 
  format: { with: /\A(.+)@(.+)\z/, message: "Email invalid"  },
  uniqueness: { case_sensitive: false },
  length: { minimum: 4, maximum: 254 }

  validates :password, length: {in: 6..20}

  # validates :user_name, presence: true, length: {maximum: 20}
  # validates :user_name, uniqueness: true, length: {in: 6..20, message: "Username's length is 6-20 characters"},
  # format: { with: /\A(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])\z/, message: "User name contains only characters a-z or numbers"}

  scope :all_except, -> (user) {where.not(id: user)}

  after_create_commit { broadcast_append_to "users" }

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    puts current_user
    @message = current_user.messages.create(body: msg_params[:body], room_id: params[:room_id])
  end

  def msg_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def index
    @room = Room.new
    @rooms = Room.public_rooms

    @users = User.all_except(current_user)
  end

  def show
    @single_room = Room.find(params[:id])

    @room = Room.new
    @rooms = Room.public_rooms

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)


    @users = User.all_except(current_user)
    render 'index'
  end

  def create
    @room = Room.create(name: params["room"]["name"])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @room = Room.new
    @rooms = Room.public_rooms

    @room_name = get_name(@user, current_user);
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    render 'rooms/index'
  end

  private
  def get_name(user1, user2) 
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Chatter</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class: 'd-flex',
  data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f|%>
    <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
    <%= f.submit data: {disable_with: false}, class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: 'd-flex',
data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f| %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.submit data: {disable_with: false}%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      <%= ".msg-#{current_user&.id}"%> {
        background-color: #007bff !important;
        padding: 10px;
      }
      <%= ".cont-#{current_user&.id}"%> {
        display: flex;
        justify-content: flex-end;
      }
    </style>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id%>">
  <div class="message-box msg-<%= message.user.id%>">
    <% unless message.room.is_private %>
      <h6 class="name text-white">
        <%= message.user.email%>
      </h6>
    <% end %>
    <%= message.body %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Chatter</h1>
<p>Find me in app/views/pages/home.html.erb</p>


<% if current_user %>
  <%= link_to "Start to chatting", rooms_path %>
  <%= button_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>

app/views/rooms/_room.html.erb
<div>
  <%= link_to room.name, room%>
</div>

app/views/rooms/index.html.erb
<div id="chatroom_container" class="row bg_dark text-light">
  <div id="side_panel" class="col-md-4 col-sm-4">
    <h5>
      <%= current_user.email %>
    </h5>
    <h4>Users</h4>
    <%= turbo_stream_from "users" %>
    <div id="users">
      <%= render @users %>
    </div>

    <h4>Rooms</h4>
    <%= turbo_stream_from "rooms" %>
    <div id="rooms">
      <%= render @rooms %>
    </div>

    <%= render 'layouts/new_room_form' %>
  </div>
  <div class="col-md-8 col-sm-8 bg-dark text-light">
    <% if @single_room %>
    <div id="single_room">
      <h4 class="text-center text-white">
        <%= @user&.email || @single_room.name %>  
      </h4>
      <%= turbo_stream_from @single_room%>
      <div id="messages" data-controller="scroll">
        <%= render @messages%>
      </div>
      <%= render 'layouts/new_message_form' %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div>
  <%= link_to user.email, user %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>